// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfLSHldrP5x83L3cPhAxFuJjCWx5mt4Hc',
    appId: '1:914739244725:web:448efc03431ca112c358fc',
    messagingSenderId: '914739244725',
    projectId: 'fd90tj',
    authDomain: 'fd90tj.firebaseapp.com',
    storageBucket: 'fd90tj.appspot.com',
    measurementId: 'G-LM92PQN8Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcNdeXybzRfrqKWUZJ2H_sNIApZrQd8HI',
    appId: '1:914739244725:android:4d76e31fadc91147c358fc',
    messagingSenderId: '914739244725',
    projectId: 'fd90tj',
    storageBucket: 'fd90tj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqbB5IX36DFgXEFqedrkLd3OWVKiOJMOo',
    appId: '1:914739244725:ios:8ef370380000d635c358fc',
    messagingSenderId: '914739244725',
    projectId: 'fd90tj',
    storageBucket: 'fd90tj.appspot.com',
    iosBundleId: 'com.example.fd9otj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqbB5IX36DFgXEFqedrkLd3OWVKiOJMOo',
    appId: '1:914739244725:ios:c5b44bac07283834c358fc',
    messagingSenderId: '914739244725',
    projectId: 'fd90tj',
    storageBucket: 'fd90tj.appspot.com',
    iosBundleId: 'com.example.fd9otj.RunnerTests',
  );
}
